In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Input

In [ ]:
x = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6],
])


# x = np.array([
#     [
#         [1],
#         [2],
#         [3]
#     ],
#     [
#         [2],
#         [3],
#         [4]
#     ],
#     [
#         [3],
#         [4],
#         [5]
#     ],
#     [
#         [4],
#         [5],
#         [6]
#     ]
# ])

y = np.array([4,5,6,7])

x = x.reshape(-1,3,1) # 굳이 위에와 같이 데이터를 바꾸지 않아도 reshape를 사용하여 변환시킬 수 있음 

print(x)
print(x.shape)  

model = Sequential([
    Input(shape=(3,1)),
    SimpleRNN(2),
    Dense(1)
])

model.summary()

model.compile(
    optimizer="adam",
    loss="mse"    
)

model.fit(
    x,
    y,
    epochs=300,
    verbose=1
)


[[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]

 [[3]
  [4]
  [5]]

 [[4]
  [5]
  [6]]]
(4, 3, 1)


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_6 (SimpleRNN)        │ (None, 2)              │             8 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11 (44.00 B)

 Trainable params: 11 (44.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 27.8382
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 27.6435
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 27.4507
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 27.2600
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - loss: 27.0715
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 26.8850
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 26.7008
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 26.5186
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 26.3385
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 26.1605
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 25.9845
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 25.8106
Epoch 13/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 25.6387
Epoch 14/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 25.4688
Epoch 15/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 25.3011
E

In [ ]:
# 예측
x_pred = np.array([[5,6,7]]).reshape(-1,3,1)
# pred = model.predict(np.array([[[5],[6],[7]]]))
pred = model.predict(x_pred)

# 두 개의 출력의 값이 똑같음

print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
[[2.5268788]]


In [ ]:
# 주식 종가 예측

x = np.array([
    [50000, 51000, 52000, 53000],
    [51000, 52000, 53000, 54000],
    [52000, 53000, 54000, 55000]
])

# 다음 날 종가
y = np.array([
    54000,
    55000,
    56000
])

x = x.reshape(-1,4,1)  # x = x.reshape(3,4,1)으로 해도 되긴 함, -1은 알아서 자동으로 맞춰줌 => 잘 모르겠으면 -1 하는 것이 좋음
print(x)
print(x.shape)

# 모델 생성

# data_size = 3
# time_steps = 4
# features = 1 ( 종가만 사용)

model = Sequential([
    Input(shape=(4,1)),
    SimpleRNN(4, activation="relu"),  # 시간과 관련하여 예측하는 건 RNN을 대부분 기본적으로 사용함
    Dense(1)
])

model.compile(
    optimizer="adam",
    loss="mse"
)

model.summary()

model.fit(
    x,
    y,
    epochs=500,
    verbose=1
)

#[53000,54000,55000,56000]


[[[50000]
  [51000]
  [52000]
  [53000]]

 [[51000]
  [52000]
  [53000]
  [54000]]

 [[52000]
  [53000]
  [54000]
  [55000]]]
(3, 4, 1)


Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_13 (SimpleRNN)       │ (None, 8)              │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 89 (356.00 B)

 Trainable params: 89 (356.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 19800393728.0000
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 19372212224.0000
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 18954237952.0000
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 18546407424.0000
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 18148628480.0000
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 17760800768.0000
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 17382778880.0000
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 17014407168.0000
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 16655482880.0000
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 16305782784.0000
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 15965056000.0000
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 15633022976.0000
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 15309396992.0000
Epoch 14/500
1/1 ━━━━━━

In [27]:
x_preb = np.array([[53000,54000,55000,56000]]).reshape(-1,4,1)
preb = model.predict(x_preb)
print("다음 날 예상 종가 :",preb)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
다음 날 예상 종가 : [[57086.75]]


In [ ]:
# Feature 1 : 온도 (Temperature)
# Feature 2 : 습도 (Humidity)

# 즉, 3일간의 온도와 습도를 보고 다음 날의 온도를 예측하시오

# [온도, 습도]
x = np.array([
    [[20,60],[21,61],[22,62]],
    [[23,63],[24,64],[25,65]],
    [[26,66],[27,67],[28,68]]
])

# 다음 날 온도
y = np.array([
    23,
    26,
    29
])

model = Sequential([
    Input(shape=(3,2)),
    SimpleRNN(8,activation="relu"),
    Dense(1)
])

model.compile(
    optimizer="adam",
    loss="mse"
)

model.summary()

model.fit(
    x,
    y,
    epochs=500,
    verbose=1
)
# 예측하시오
#    [[29,69],
#      [30,70],
#      [31,71]]


Model: "sequential_28"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_28 (SimpleRNN)       │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_28 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 2801.9324
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2590.4011
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2386.7703
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2191.2446
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2004.0192
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1825.2642
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 1655.1300
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 1493.7511
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1341.2313
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 1197.6462
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1063.0448
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 937.4435
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 820.8220
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 713.1252
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/st

In [57]:
pred = model.predict(np.array([[[29,69],[30,70],[31,71]]]))
print("예상 온도 : ", pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step
예상 온도 :  [[32.346985]]


In [ ]:
# ==========================================
# 1. 데이터 준비
# ==========================================

# [키(cm), 몸무게(kg), 나이]
x = np.array([
    [[170,60,20], [171,61,21]],
    [[180,70,30], [181,71,31]],
    [[190,80,40], [191,81,41]],
    [[200,90,50], [201,91,51]]
])

# 다음 해 키
y = np.array([
    [172,62],
    [182,72],
    [192,82],
    [202,92]
])

x = x.reshape(-1,2,3)
print("===== 입력 데이터 =====")
print(x)

print("\nShape :", x.shape)


model = Sequential([
    Input(shape=(2,3)),
    SimpleRNN(16, activation="relu"),
    Dense(2)  # 예측하는 컬럼이 2개 이므로 2가 됨
])

model.summary()

model.compile(
    optimizer="adam",
    loss="mse"
)

model.fit(
    x,
    y,
    epochs=500,
    verbose=1
)



===== 입력 데이터 =====
[[[170  60  20]
  [171  61  21]]

 [[180  70  30]
  [181  71  31]]

 [[190  80  40]
  [191  81  41]]

 [[200  90  50]
  [201  91  51]]]

Shape : (4, 2, 3)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_4 (SimpleRNN)        │ (None, 16)             │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 2)              │            34 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 354 (1.38 KB)

 Trainable params: 354 (1.38 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 24458.6934
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 23920.0000
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 23389.5234
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 22867.3711
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 22370.7734
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 21901.4863
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 21440.5859
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 21011.2031
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 20596.0430
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 20188.7812
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 19783.1445
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 19396.3965
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 19014.7832
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 18638.2480
Epoch 15/500
1/1 ━━━━━━━━━━━━━━

In [16]:
x_pred = np.array([
    [[175,65,25],
    [176,66,26]]    
])


pred = model.predict(x_pred)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step
[[177.03963   68.141716]]
