In [ ]:
import numpy as np 

arr = np.array([0,1,2,3,4])

# 넘파이 배열을 읽는 방법은 리스트의 인덱싱과 같음
print(arr[2])
print(arr[0])
print(arr[-1])
print(arr.dtype)

arr =  np.array([
                    [0, 1, 2], 
                    [3, 4, 5]
                ])
# 문제
# 1) 해당 배열의 차원을 출력하시오 (2,3)
# 2) 0을 뽑아 내시오
# 3) 5를 뽑아 내시오
print(arr.ndim)
print(arr[0,0])
print(arr[1,2]) # print(arr[-1][-1])도 가능

# 넘파이는 좌표 방식 접근도 지원
print(arr[0,0])


2
0
4
int64
2
0
5


In [ ]:
# 슬라이싱

arr = np.array([10,20,30,40,50,60,70])
print("원본 배열",arr)

# 인덱스 4부터 끝까지
print(arr[4:])

# 인덱스 1부터 3까지 (1부터 4 사이)
print(arr[1:4])

# 처음부터 끝까지, 2칸씩 건너뛰기
print(arr[::2])


원본 배열 [10 20 30 40 50 60 70]
[50 60 70]
[20 30 40]
[10 30 50 70]
[10 30 50]


In [8]:
# 2차원 배열에서 슬라이싱
arr = np.array([
                    [0, 1, 2, 3], 
                    [4, 5, 6, 7]
                ])
print(arr.shape)

# 첫 번째 행 전체 [0,1,2,3]
print(arr[0,:])
print(arr[0][:])

# 두 번째 행 전체 [4,5,6,7]
print(arr[1,:])
print(arr[1][:])

# 두 번째 열 전체 [1,5]
print(arr[:,1])

# 두 번재 행의 두번재 열부터 끝열 까지 [5,6]
print(arr[1,1:3]) # print(arr[1,1:])도 가능


(2, 4)
[0 1 2 3]
[0 1 2 3]
[4 5 6 7]
[4 5 6 7]
[1 5]
[5 6]
