In [ ]:
# 넘파이 연산
# 행렬 연산을 기반으로 함
import numpy as np

arr1 = np.array([
                    [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]
                ])

arr2 = np.array([
                    [2, 2, 2],
                    [2, 2, 2],
                    [2, 2, 2]]
                )
# [[ 3  4  5]
#  [ 6  7  8]
#  [ 9 10 11]]
print(arr1 + arr2)
print(arr1.__add__(arr2))
print(np.add(arr1,arr2))
# 3가지 다 똑같음

# [[-1  0  1]
#  [ 2  3  4]
#  [ 5  6  7]]
print(arr1 - arr2)
print(np.subtract(arr1,arr2))

# * => 원소끼리 곱 )Element-wise)
# 즉 위치가 같은 값끼리 곱함
# 기본적인 데이터 분석에서 사용
# 하나씩 대응

# [[ 2  4  6]
#  [ 8 10 12]
#  [14 16 18]]
print(arr1 * arr2)
print(np.multiply(arr1,arr2))

# @ => 행렬 곱 (Matrix Multiplication)
# 수학에서의 행렬 곱
# 변환, 계산, 예측 (머신러닝, 딥러닝)등 수학적 기반에서 사용 = 선형대수
# 가중치 = 재료들을 섞어서 새로운 값 생성

# [[12 12 12]
#  [30 30 30]
#  [48 48 48]]
print(arr1 @ arr2)
print(np.matmul(arr1,arr2))


[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[12 12 12]
 [30 30 30]
 [48 48 48]]
[[12 12 12]
 [30 30 30]
 [48 48 48]]


In [13]:
# 스칼라(상수) 와의 곱
print(3 * arr1) # 브로드 캐스팅
print(3 + arr1) 

a = [1, 2]
print(a * 2) # 리스트에 곱하면 요소가 2번 반복됨, 산수를 진행하는게 아님 => [1,2,1,2]
print(np.array(a)*3) # 리스트 a를 넘파이 배열로 바꾸면 수학적 계산이 진행됨  => [3,6]



[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1, 2, 1, 2]
[3 6]


In [18]:
# 몫과 나머지
print(arr2 // 2) # 몫의 정수 값
print(arr2 % 2) # 나머지

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
