In [ ]:
# 넘파이 정렬
import numpy as np

arr = np.random.randint(10,size=10)
# 원본을 바꿈 => arr.sort( )
print(arr)
print(arr.sort()) # 리턴 값을 제공해주지 않아서 (None으로 표시) 다시 프린트 진행해야함
print(arr) # 원본 값을 바꿈

print(np.sort(arr)) # 원본에 영향을 주지 않음
print(arr)

[2 6 2 2 2 3 2 2 8 6]
None
[2 2 2 2 2 2 3 6 6 8]
[2 2 2 2 2 2 3 6 6 8]
[2 2 2 2 2 2 3 6 6 8]


In [ ]:
# 내림 차순
print(np.sort(arr)[::-1]) # 뒤에 [::-1]을 붙히지 않으면 오름차순
arr2 = np.sort(arr)[::-1]
print(arr2)

[8 6 6 3 2 2 2 2 2 2]
[8 6 6 3 2 2 2 2 2 2]


In [ ]:
np.random.seed(42)
# 2차원 배열 정렬
arr = np.random.randint(15,size=(3,4))
print(arr)

# 행단위 정렬
print(np.sort(arr,axis=1)) # 원본에서 행단위로 정렬

# 열단위 정렬
print(np.sort(arr,axis=0)) # 원본에서 열단위로 정렬 

# axis 숫자는 "없어지는 축 번호"
# axis = 0 은 행을 지우는 것 => 세로 계산
# axis = 1 은 열을 지우는 것 => 가로 계산

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]]
[[ 3  6 12 14]
 [ 4  7 10 12]
 [ 2  6  6  9]]
[[ 6  3  2  4]
 [ 6  7 12  6]
 [10  9 12 14]]
