In [ ]:
import numpy as np

arr = np.array([
                    [1, 2, 3], 
                    [0, 1, 4]
               ])

# 배열 전체에서 최소값 찾기
print(np.min(arr))
print(arr.min())

 
print(arr.min(axis=0)) # 열단위 최소값  # [0 1 3]
print(arr.min(axis=1)) # 행단위 최소값 #[1 0]

print(np.max(arr))
print(arr.max())

print(arr.max(axis=0)) # 열단위 최대값  # [1 2 4]
print(arr.max(axis=1)) # 행단위 최대값 #[3 4]

# 원소합
print(np.sum(arr))
print(arr.sum())

print(arr.sum(axis=0)) # 열단위 합 # [1 3 7]
print(arr.sum(axis=1)) # 행단위 합 # [6 5]

# 누적 합계
# cumulative sum, 누적 합계
# 앞에서 부터 차례로 더한 값을 반환
print(np.cumsum(arr)) # [ 1  3  6  6  7 11]
print(arr.cumsum())

print(arr.cumsum(axis=0)) # 각 열에 대한 모든 행에서 동작
# [[1 2 3]
#  [1 3 7]]
print(arr.cumsum(axis=1)) # 각 행에 대한 모든 열에서 동작
# [[1 3 6]
#  [0 1 5]]

In [ ]:
# 평균 / 표준편차 / 중앙값
print(np.mean(arr))
print(arr.mean()) # 1.8333333333333333
print(arr.mean(axis=0)) # [0.5 1.5 3.5]
print(arr.mean(axis=1)) # [2.         1.66666667]

# 표준편차
# 데이터가 평균으로부터 얼마나 퍼져있는지 측정하는 값
print(np.std(arr))
print(arr.std()) # 1.343709624716425
print(arr.std(axis=0)) # [0.5 0.5 0.5]
print(arr.std(axis=1)) # [0.81649658 1.69967317]

# 분산
print(np.var(arr))
print(arr.var()) # 1.805555555555556
print(arr.var(axis=0)) # [0.25 0.25 0.25]
print(arr.var(axis=1)) # [0.66666667 2.88888889]

# 중앙값 
# [[1 2 3]
#  [0 1 4]]

# 1 2 3 0 1 4 - 그냥 일렬로 펼친 것
# 0 1 1 2 3 4 (정렬) => 홀수일때는 위치 정가운데 숫자, 짝수일때는 가운데 두 숫자의 평균

print(arr)
print(np.median(arr)) # 1.5 (가운데 두 숫자가 1,2 라서 평균 1.5)

print(np.median(arr,axis=1)) # 행 기준 = [2 1]
print(np.median(arr,axis=0)) # 열 기준 = [0.5 1.5 3.5]

1.8333333333333333
1.8333333333333333
[0.5 1.5 3.5]
[2.         1.66666667]
1.343709624716425
1.343709624716425
[0.5 0.5 0.5]
[0.81649658 1.69967317]
1.805555555555556
1.805555555555556
[0.25 0.25 0.25]
[0.66666667 2.88888889]
[[1 2 3]
 [0 1 4]]
1.5
[2. 1.]
[0.5 1.5 3.5]
