In [18]:
import numpy as np

arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
arr.reshape(3,4) # 원본은 바뀌지 않음

print(arr)

arr.reshape(-1,4) # 4열로 해서 알아서 행을 맞춰주라는 의미, 생각보다 많이 쓰임
arr.reshape(2,-1) # 마찬가지로 2행만 맞추고 나머지는 알아서

arr = np.array([
                    [1, 2, 3], 
                    [0, 1, 4]
               ])

arr.flatten() # 1차원 배열로 만드는 함수

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([1, 2, 3, 0, 1, 4])